### PR TITLE
Only allow a single media element to play at a time

### PR DESCRIPTION
**Pull request by hpeebles**

### CODE REVIEW

**Review by julianjelfs — COMMENTED** [review]
There is actually an example in the svelte docs to do exactly this: https://learn.svelte.dev/tutorial/sharing-code

**Comment by hpeebles** [comment]
> There is actually an example in the svelte docs to do exactly this: https://learn.svelte.dev/tutorial/sharing-code

That example only works if a single instance of that single component can play media. But in our case there can be multiple AudioContent components and multiple VideoContent components, any of which could be playing.

**Comment by hpeebles** [comment]
> > There is actually an example in the svelte docs to do exactly this: https://learn.svelte.dev/tutorial/sharing-code
> 
> That example only works if a single instance of that single component can play media. But in our case there can be multiple AudioContent components and multiple VideoContent components, any of which could be playing.

Ah no actually I understood it wrong on first look. It may work...

**Review by julianjelfs — APPROVED** [review]

**Comment by julianjelfs** [comment]
Just thinking we should probably pause media using an intersection observer as well so they stop when they go off the screen.

**Pull request merged**
